/*
 * Copyright (C) 2026  Argon4W
 *
 * This file is part of RenderFox.
 *
 * RenderFox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RenderFox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with RenderFox.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.github.argon4w.renderfox.opengl.function.parameter;

import it.unimi.dsi.fastutil.ints.Int2ReferenceMap;
import it.unimi.dsi.fastutil.ints.Int2ReferenceOpenHashMap;
import org.lwjgl.opengl.*;

public enum GLGlobalParameter implements IGLParameter {

	INVALID									(-1),
	UNIFORM_BUFFER_OFFSET_ALIGNMENT			(GL31.GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT),
	SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT	(GL43.GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT),
	MAX_UNIFORM_BUFFER_BINDINGS				(GL31.GL_MAX_UNIFORM_BUFFER_BINDINGS),
	MAX_SHADER_STORAGE_BUFFER_BINDINGS		(GL43.GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS),
	MAX_ATOMIC_COUNTER_BUFFER_BINDINGS		(GL42.GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS),
	VERTEX_BUFFER_BINDING					(GL15.GL_ARRAY_BUFFER_BINDING),
	ELEMENT_BUFFER_BINDING					(GL15.GL_ELEMENT_ARRAY_BUFFER_BINDING),
	DISPATCH_INDIRECT_BUFFER_BINDING		(GL43.GL_DISPATCH_INDIRECT_BUFFER_BINDING),
	PARAMETER_BUFFER_BINDING				(GL46.GL_PARAMETER_BUFFER_BINDING),
	DRAW_INDIRECT_BUFFER_BINDING			(GL40.GL_DRAW_INDIRECT_BUFFER_BINDING),
	COPY_READ_BUFFER_BINDING				(GL42.GL_COPY_READ_BUFFER_BINDING),
	COPY_WRITE_BUFFER_BINDING				(GL42.GL_COPY_WRITE_BUFFER_BINDING),
	TEXTURE_BUFFER_BINDING					(GL44.GL_TEXTURE_BUFFER_BINDING),
	PIXEL_PACK_BUFFER_BINDING				(GL21.GL_PIXEL_PACK_BUFFER_BINDING),
	PIXEL_UNPACK_BUFFER_BINDING				(GL21.GL_PIXEL_UNPACK_BUFFER_BINDING),
	TEXTURE_1D_BINDING						(GL11.GL_TEXTURE_BINDING_1D),
	TEXTURE_2D_BINDING						(GL11.GL_TEXTURE_BINDING_2D),
	TEXTURE_3D_BINDING						(GL12.GL_TEXTURE_BINDING_3D),
	TEXTURE_1D_ARRAY_BINDING				(GL30.GL_TEXTURE_BINDING_1D_ARRAY),
	TEXTURE_2D_ARRAY_BINDING				(GL30.GL_TEXTURE_BINDING_2D_ARRAY),
	TEXTURE_RECTANGLE_BINDING				(GL31.GL_TEXTURE_BINDING_RECTANGLE),
	TEXTURE_CUBE_MAP_BINDING				(GL13.GL_TEXTURE_BINDING_CUBE_MAP),
	TEXTURE_CUBE_MAP_ARRAY_BINDING			(GL40.GL_TEXTURE_BINDING_CUBE_MAP_ARRAY),
	TEXTURE_2D_MULTISAMPLE_BINDING			(GL32.GL_TEXTURE_BINDING_2D_MULTISAMPLE),
	TEXTURE_2D_MULTISAMPLE_ARRAY_BINDING	(GL32.GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY),
	ACTIVE_TEXTURE							(GL13.GL_ACTIVE_TEXTURE),
	MAX_COMBINED_TEXTURE_IMAGE_UNITS		(GL20.GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS),
	MAX_TEXTURE_SIZE						(GL11.GL_MAX_TEXTURE_SIZE),
	MAX_3D_TEXTURE_SIZE						(GL12.GL_MAX_3D_TEXTURE_SIZE),
	MAX_CUBE_MAP_TEXTURE_SIZE				(GL13.GL_MAX_CUBE_MAP_TEXTURE_SIZE),
	MAX_ARRAY_TEXTURE_LAYERS				(GL30.GL_MAX_ARRAY_TEXTURE_LAYERS),
	MAX_DEPTH_TEXTURE_SAMPLES				(GL32.GL_MAX_DEPTH_TEXTURE_SAMPLES),
	MAX_COLOR_TEXTURE_SAMPLES				(GL32.GL_MAX_COLOR_TEXTURE_SAMPLES),
	MAX_INTEGER_SAMPLES						(GL32.GL_MAX_INTEGER_SAMPLES),
	MAX_TEXTURE_MAX_ANISOTROPY				(ARBTextureFilterAnisotropic.GL_MAX_TEXTURE_MAX_ANISOTROPY),
	SAMPLER_BINDING							(GL33.GL_SAMPLER_BINDING),
	PACK_SWAP_BYTES							(GL11.GL_PACK_SWAP_BYTES),
	PACK_LSB_FIRST							(GL11.GL_PACK_LSB_FIRST),
	PACK_ROW_LENGTH							(GL11.GL_PACK_ROW_LENGTH),
	PACK_IMAGE_HEIGHT						(GL12.GL_PACK_IMAGE_HEIGHT),
	PACK_SKIP_ROWS							(GL11.GL_PACK_SKIP_ROWS),
	PACK_SKIP_PIXELS						(GL11.GL_PACK_SKIP_PIXELS),
	PACK_SKIP_IMAGES						(GL12.GL_PACK_SKIP_IMAGES),
	PACK_ALIGNMENT							(GL11.GL_PACK_ALIGNMENT),
	UNPACK_SWAP_BYTES						(GL11.GL_UNPACK_SWAP_BYTES),
	UNPACK_LSB_FIRST						(GL11.GL_UNPACK_LSB_FIRST),
	UNPACK_ROW_LENGTH						(GL11.GL_UNPACK_ROW_LENGTH),
	UNPACK_IMAGE_HEIGHT						(GL12.GL_UNPACK_IMAGE_HEIGHT),
	UNPACK_SKIP_ROWS						(GL11.GL_UNPACK_SKIP_ROWS),
	UNPACK_SKIP_PIXELS						(GL11.GL_UNPACK_SKIP_PIXELS),
	UNPACK_SKIP_IMAGES						(GL12.GL_UNPACK_SKIP_IMAGES),
	UNPACK_ALIGNMENT						(GL11.GL_UNPACK_ALIGNMENT),
	FRAMEBUFFER_BINDING						(GL30.GL_FRAMEBUFFER_BINDING),
	READ_FRAMEBUFFER_BINDING				(GL30.GL_READ_FRAMEBUFFER_BINDING),
	DRAW_FRAMEBUFFER_BINDING				(GL30.GL_DRAW_FRAMEBUFFER_BINDING),
	MAX_DRAW_BUFFERS						(GL20.GL_MAX_DRAW_BUFFERS),
	MAX_COLOR_ATTACHMENTS					(GL30.GL_MAX_COLOR_ATTACHMENTS),
	MAX_FRAMEBUFFER_WIDTH					(GL43.GL_MAX_FRAMEBUFFER_WIDTH),
	MAX_FRAMEBUFFER_HEIGHT					(GL43.GL_MAX_FRAMEBUFFER_HEIGHT),
	MAX_FRAMEBUFFER_LAYERS					(GL43.GL_MAX_FRAMEBUFFER_LAYERS),
	MAX_FRAMEBUFFER_SAMPLES					(GL43.GL_MAX_FRAMEBUFFER_SAMPLES),
	READ_BUFFER								(GL11.GL_READ_BUFFER),
	DRAW_BUFFER_0							(GL20.GL_DRAW_BUFFER0),
	DRAW_BUFFER_1							(GL20.GL_DRAW_BUFFER1),
	DRAW_BUFFER_2							(GL20.GL_DRAW_BUFFER2),
	DRAW_BUFFER_3							(GL20.GL_DRAW_BUFFER3),
	DRAW_BUFFER_4							(GL20.GL_DRAW_BUFFER4),
	DRAW_BUFFER_5							(GL20.GL_DRAW_BUFFER5),
	DRAW_BUFFER_6							(GL20.GL_DRAW_BUFFER6),
	DRAW_BUFFER_7							(GL20.GL_DRAW_BUFFER7),
	DRAW_BUFFER_8							(GL20.GL_DRAW_BUFFER8),
	DRAW_BUFFER_9							(GL20.GL_DRAW_BUFFER9),
	DRAW_BUFFER_10							(GL20.GL_DRAW_BUFFER10),
	DRAW_BUFFER_11							(GL20.GL_DRAW_BUFFER11),
	DRAW_BUFFER_12							(GL20.GL_DRAW_BUFFER12),
	DRAW_BUFFER_13							(GL20.GL_DRAW_BUFFER13),
	DRAW_BUFFER_14							(GL20.GL_DRAW_BUFFER14),
	DRAW_BUFFER_15							(GL20.GL_DRAW_BUFFER15);

	private	static final Int2ReferenceMap<GLGlobalParameter>	TABLE;
	public	static final GLGlobalParameter[]					DRAW_BUFFERS;

	static {
		TABLE			= new Int2ReferenceOpenHashMap<>();
		DRAW_BUFFERS	= new GLGlobalParameter			[16];

		DRAW_BUFFERS[0]		= DRAW_BUFFER_0;
		DRAW_BUFFERS[1]		= DRAW_BUFFER_1;
		DRAW_BUFFERS[2]		= DRAW_BUFFER_2;
		DRAW_BUFFERS[3]		= DRAW_BUFFER_3;
		DRAW_BUFFERS[4]		= DRAW_BUFFER_4;
		DRAW_BUFFERS[5]		= DRAW_BUFFER_5;
		DRAW_BUFFERS[6]		= DRAW_BUFFER_6;
		DRAW_BUFFERS[7]		= DRAW_BUFFER_7;
		DRAW_BUFFERS[8]		= DRAW_BUFFER_8;
		DRAW_BUFFERS[9]		= DRAW_BUFFER_9;
		DRAW_BUFFERS[10]	= DRAW_BUFFER_10;
		DRAW_BUFFERS[11]	= DRAW_BUFFER_11;
		DRAW_BUFFERS[12]	= DRAW_BUFFER_12;
		DRAW_BUFFERS[13]	= DRAW_BUFFER_13;
		DRAW_BUFFERS[14]	= DRAW_BUFFER_14;
		DRAW_BUFFERS[15]	= DRAW_BUFFER_15;

		for (var globalConstant : GLGlobalParameter.values()) {
			TABLE.put(globalConstant.constant, globalConstant);
		}
	}

	private final int constant;

	GLGlobalParameter(int constant) {
		this.constant = constant;
	}

	@Override
	public int getConstant() {
		return constant;
	}

	public static GLGlobalParameter fromConstant(int constant) {
		return TABLE.getOrDefault(constant, INVALID);
	}
}
